### PR TITLE
fix: compatible with Maven 4

### PR DESCRIPTION
**Pull request by gnodet**
- **feat: support Maven 4.0**
- **back pick https://github.com/trustin/os-maven-plugin/pull/74/**
- **try test maven 4.0.0-beta-4**
- **tidy**
- **Remove the mvn4 specific bits**

### CODE REVIEW

**Comment by tisonkun** [comment]
@gnodet Thank you! I'm going to integrate with you changes, merge and release.

But still, I wonder how the removed part are "supporting Maven 4", so that I may pick up this topic later to deliver a good integration :D

**Comment by gnodet** [comment]
> @gnodet Thank you! I'm going to integrate with you changes, merge and release.
> 
> But still, I wonder how the removed part are "supporting Maven 4", so that I may pick up this topic later to deliver a good integration :D

The `PropertyContributor` is new to the Maven 4 API, so it can only be loaded if running in Maven 4, in which case, to avoid running the code twice, it disables the Maven 3 extension.  The idea was that the internals may change in Maven 4 in the future and the Maven 3 extension may not work anymore with Maven 4 in the future.  
However, things have changed a lot since I worked on that, and the Maven 4 extension should be rewritten anyway.

**Comment by tisonkun** [comment]
> the Maven 4 extension should be rewritten anyway.

Yes. As long as Maven 4 is released or the API is relatively stable, and there are enough docs to start with, I'd write a `plugin-maven-4` for it.

**Comment by tisonkun** [comment]
OK. Then Let me merge and release this patch today. Thanks again for your information.

**Comment by tisonkun** [comment]
I found that this is actually a fix. So I publish 0.3.1 for it.

@linghengqian you can try to replace the os-maven-plugin with:

```xml
    <build>
        <extensions>
            <extension>
                <groupId>com.tisonkun.os</groupId>
                <artifactId>os-detector-maven-plugin</artifactId>
                <version>0.3.1</version>
            </extension>
        </extensions>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.apache.opendal</groupId>
            <artifactId>opendal</artifactId>
            <version>${opendal.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.opendal</groupId>
            <artifactId>opendal</artifactId>
            <version>${opendal.version}</version>
            <classifier>${os.detected.classifier}</classifier>
        </dependency>
    </dependencies>
```

The same user experience.

**Comment by tisonkun** [comment]
Before release a 1.0, I'd try to find some time consider #6 and #7. And always try to seek the opportunity to work with both Trustin and Google (the upstream) so that we merge the community instead of fork another ..

**Comment by linghengqian** [comment]
> @linghengqian you can try to replace the os-maven-plugin with:

- Great! Let’s go back to the original post https://github.com/apache/opendal/discussions/5133#discussioncomment-10739653 .

**Pull request merged**
